apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dd-app-api-hpa
  namespace: default
  labels:
    app: dd-app-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dd-app-api

  # Minimum and maximum number of replicas
  minReplicas: 2
  maxReplicas: 10

  # Scaling behavior configuration
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 50  # Scale down by 50% of current pods
        periodSeconds: 60
      - type: Pods
        value: 2  # Or scale down by 2 pods
        periodSeconds: 60
      selectPolicy: Min  # Choose the policy that scales down the least

    scaleUp:
      stabilizationWindowSeconds: 0  # Scale up immediately when needed
      policies:
      - type: Percent
        value: 100  # Double the number of pods
        periodSeconds: 30
      - type: Pods
        value: 4  # Or add 4 pods
        periodSeconds: 30
      selectPolicy: Max  # Choose the policy that scales up the most

  # Metrics to watch for autoscaling
  metrics:
  # CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scale when average CPU > 70%

  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # Scale when average memory > 80%

---
# Alternative: Simple HPA configuration (uncomment to use)
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: dd-app-api-hpa-simple
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: dd-app-api
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 50
