apiVersion: v1
kind: Service
metadata:
  name: user-auth-service-nodeport
  labels:
    app: user-auth-service-nodeport
spec:
  type: NodePort
  selector:
    app: user-auth
  ports:
    - name: auth
      port: 3002
      targetPort: 3002
      nodePort: 30002
      protocol: TCP
