apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
  labels:
    app: user-auth-service
spec:
  type: ClusterIP
  selector:
    app: user-auth
  ports:
    - name: auth
      port: 3002
      targetPort: 3002
      protocol: TCP
