apiVersion: v1
kind: Pod
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  containers:
    - name: order-service
      image: "order-service:latest"
      imagePullPolicy: Never
      ports:
        - containerPort: 3001
          name: http
      env:
        - name: PORT
          value: "3001"
        - name: NODE_ENV
          value: "development"
        - name: DD_SERVICE
          value: "order-service"
        - name: DD_VERSION
          value: "1.0.0"
        - name: DD_ENV
          value: "development"
        - name: DD_TRACE_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_PROFILING_ENABLED
          value: "true"
